# Site Settings
title:               The Blue Pill
tagline:             non-controversial thoughts on everything!
description:
baseurl:            #"/"
url:                #"https://hypoalex.github.io"
github:
  url:               "http://hypoalex.github.io"
author:
  name:              "Alex Caudill"
  email:             "alex@memphisinsights.com"
  twitter:           "hypoalex"
  instagram:         "memphisinsights"
  github:            "hypoalex"
  facebook:          "evl.alexander"
  linkedin:          "hypoalex"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
