# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Red Pill
#email: saepenumera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Explorations of data science, math, code, and... everything else!
baseurl: "http://hypoalex.github.io/" # the subpath of your site, e.g. /blog
url: "http://hypoalex.github.io" # the base hostname & protocol for your site
twitter_username: hypoalex
github_username:  hypoalex

# Build settings
markdown: kramdown
